"use client"

export const LOCAL_DB_VERSION = 6
export const LOCAL_DB_URL = "sqlite:bezgrow-offline.db"

export const normalizedTables = [
  "organizations",
  "business_settings",
  "local_users",
  "roles",
  "permissions",
  "role_permissions",
  "organization_members",
  "feature_flags",
  "categories",
  "units",
  "products",
  "customers",
  "suppliers",
  "warehouses",
  "inventory_items",
  "stock_batches",
  "stock_movements",
  "sales_invoices",
  "sales_invoice_items",
  "purchase_invoices",
  "purchase_invoice_items",
  "orders",
  "order_items",
  "quotations",
  "quotation_items",
  "delivery_challans",
  "delivery_challan_items",
  "credit_notes",
  "credit_note_items",
  "debit_notes",
  "debit_note_items",
  "expenses",
  "payments",
  "payment_receipts",
  "ledger_entries",
  "chart_of_accounts",
  "accounting_vouchers",
  "accounting_voucher_entries",
  "bank_accounts",
  "gst_tax_rates",
  "gst_invoice_summary",
  "gst_hsn_summary",
  "print_templates",
  "license_state",
  "device_activations",
  "local_audit_logs",
  "backup_manifest",
  "offline_sync_queue",
  "offline_sync_action_fields",
  "offline_sync_conflicts",
  "offline_sync_conflict_fields",
  "offline_sync_logs",
  "offline_sync_log_fields",
] as const

const commonSyncColumns = `
  sync_status TEXT NOT NULL DEFAULT 'synced',
  offline_local_id TEXT,
  server_id TEXT,
  last_synced_at TEXT,
  created_at TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at TEXT NOT NULL DEFAULT (datetime('now')),
  deleted_at TEXT
`

export const localMigrations: Array<{ version: number; name: string; sql: string[] }> = [
  {
    version: 1,
    name: "normalized_offline_erp_foundation",
    sql: [
      `CREATE TABLE IF NOT EXISTS schema_migrations (
        version INTEGER PRIMARY KEY,
        name TEXT NOT NULL,
        applied_at TEXT NOT NULL DEFAULT (datetime('now'))
      )`,
      `CREATE TABLE IF NOT EXISTS database_health (
        id TEXT PRIMARY KEY,
        check_name TEXT NOT NULL,
        status TEXT NOT NULL,
        detail TEXT,
        checked_at TEXT NOT NULL DEFAULT (datetime('now'))
      )`,
      `CREATE TABLE IF NOT EXISTS organizations (
        id TEXT PRIMARY KEY,
        owner_id TEXT,
        name TEXT NOT NULL DEFAULT 'Business',
        business_name TEXT,
        industry TEXT,
        business_type TEXT,
        business_category TEXT,
        gst_number TEXT,
        tax_id TEXT,
        phone TEXT,
        email TEXT,
        website TEXT,
        fssai TEXT,
        address TEXT,
        city TEXT,
        state TEXT,
        country TEXT,
        currency TEXT NOT NULL DEFAULT 'INR',
        timezone TEXT NOT NULL DEFAULT 'Asia/Kolkata',
        locale TEXT NOT NULL DEFAULT 'en-IN',
        branch_name TEXT DEFAULT 'Main Branch',
        invoice_prefix TEXT,
        next_invoice_number INTEGER NOT NULL DEFAULT 1,
        financial_year_start TEXT,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS business_settings (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        key TEXT NOT NULL,
        value_text TEXT,
        value_number REAL,
        value_boolean INTEGER,
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE (organization_id, key)
      )`,
      `CREATE TABLE IF NOT EXISTS local_users (
        id TEXT PRIMARY KEY,
        organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE,
        email TEXT,
        full_name TEXT,
        role TEXT NOT NULL DEFAULT 'user',
        approved INTEGER NOT NULL DEFAULT 1,
        business_created INTEGER NOT NULL DEFAULT 1,
        is_suspended INTEGER NOT NULL DEFAULT 0,
        last_login_at TEXT,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS roles (
        id TEXT PRIMARY KEY,
        organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        label TEXT,
        is_system INTEGER NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE (organization_id, name)
      )`,
      `CREATE TABLE IF NOT EXISTS permissions (
        id TEXT PRIMARY KEY,
        module TEXT NOT NULL,
        action TEXT NOT NULL,
        label TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE (module, action)
      )`,
      `CREATE TABLE IF NOT EXISTS role_permissions (
        role_id TEXT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
        permission_id TEXT NOT NULL REFERENCES permissions(id) ON DELETE CASCADE,
        PRIMARY KEY (role_id, permission_id)
      )`,
      `CREATE TABLE IF NOT EXISTS organization_members (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        user_id TEXT NOT NULL REFERENCES local_users(id) ON DELETE CASCADE,
        role TEXT NOT NULL DEFAULT 'member',
        is_active INTEGER NOT NULL DEFAULT 1,
        ${commonSyncColumns},
        UNIQUE (organization_id, user_id)
      )`,
      `CREATE TABLE IF NOT EXISTS feature_flags (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        feature_key TEXT NOT NULL,
        is_enabled INTEGER NOT NULL DEFAULT 1,
        requires_plan TEXT,
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE (organization_id, feature_key)
      )`,
      `CREATE TABLE IF NOT EXISTS categories (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        parent_id TEXT REFERENCES categories(id) ON DELETE SET NULL,
        is_active INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE (organization_id, name)
      )`,
      `CREATE TABLE IF NOT EXISTS units (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        symbol TEXT,
        precision INTEGER NOT NULL DEFAULT 2,
        is_active INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE (organization_id, name)
      )`,
      `CREATE TABLE IF NOT EXISTS suppliers (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        email TEXT,
        phone TEXT,
        gstin TEXT,
        gst_number TEXT,
        tax_id TEXT,
        address TEXT,
        city TEXT,
        state TEXT,
        country TEXT,
        opening_balance REAL NOT NULL DEFAULT 0,
        current_balance REAL NOT NULL DEFAULT 0,
        is_active INTEGER NOT NULL DEFAULT 1,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS warehouses (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        code TEXT,
        address TEXT,
        is_active INTEGER NOT NULL DEFAULT 1,
        ${commonSyncColumns},
        UNIQUE (organization_id, name)
      )`,
      `CREATE TABLE IF NOT EXISTS products (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        description TEXT,
        manufacturer TEXT,
        sku TEXT,
        barcode TEXT,
        category_id TEXT REFERENCES categories(id) ON DELETE SET NULL,
        category TEXT,
        unit_id TEXT REFERENCES units(id) ON DELETE SET NULL,
        unit TEXT DEFAULT 'pcs',
        supplier_id TEXT REFERENCES suppliers(id) ON DELETE SET NULL,
        supplier TEXT,
        warehouse_id TEXT REFERENCES warehouses(id) ON DELETE SET NULL,
        warehouse TEXT,
        hsn_code TEXT,
        price REAL NOT NULL DEFAULT 0,
        stock REAL NOT NULL DEFAULT 0,
        min_stock REAL NOT NULL DEFAULT 5,
        reserved_stock REAL NOT NULL DEFAULT 0,
        batch_no TEXT,
        mrp REAL,
        purchase_rate REAL,
        sale_rate REAL,
        gst REAL,
        expiry_date TEXT,
        purchase_date TEXT,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS customers (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        name TEXT NOT NULL,
        email TEXT,
        phone TEXT,
        gst_number TEXT,
        tax_id TEXT,
        address TEXT,
        city TEXT,
        state TEXT,
        country TEXT,
        customer_type TEXT NOT NULL DEFAULT 'retail',
        opening_balance REAL NOT NULL DEFAULT 0,
        current_balance REAL NOT NULL DEFAULT 0,
        total_sales REAL NOT NULL DEFAULT 0,
        last_purchase_at TEXT,
        is_active INTEGER NOT NULL DEFAULT 1,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS inventory_items (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
        warehouse_id TEXT REFERENCES warehouses(id) ON DELETE SET NULL,
        batch_id TEXT,
        quantity REAL NOT NULL DEFAULT 0,
        reserved_quantity REAL NOT NULL DEFAULT 0,
        available_quantity REAL NOT NULL DEFAULT 0,
        reorder_level REAL NOT NULL DEFAULT 0,
        ${commonSyncColumns},
        UNIQUE (organization_id, product_id, warehouse_id, batch_id)
      )`,
      `CREATE TABLE IF NOT EXISTS stock_batches (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE,
        warehouse_id TEXT REFERENCES warehouses(id) ON DELETE SET NULL,
        batch_no TEXT,
        manufacturing_date TEXT,
        expiry_date TEXT,
        purchase_date TEXT,
        quantity REAL NOT NULL DEFAULT 0 CHECK (quantity >= 0),
        purchase_rate REAL,
        mrp REAL,
        barcode TEXT,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS stock_movements (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        product_id TEXT REFERENCES products(id) ON DELETE SET NULL,
        product_name TEXT,
        warehouse_id TEXT REFERENCES warehouses(id) ON DELETE SET NULL,
        batch_id TEXT REFERENCES stock_batches(id) ON DELETE SET NULL,
        type TEXT NOT NULL,
        quantity REAL NOT NULL DEFAULT 0,
        previous_stock REAL,
        new_stock REAL,
        reason TEXT,
        reference_no TEXT,
        reference_type TEXT,
        reference_id TEXT,
        movement_date TEXT NOT NULL DEFAULT (date('now')),
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS sales_invoices (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        customer_id TEXT REFERENCES customers(id) ON DELETE SET NULL,
        customer_name TEXT,
        invoice_number TEXT NOT NULL,
        invoice_type TEXT NOT NULL DEFAULT 'standard',
        invoice_date TEXT NOT NULL DEFAULT (date('now')),
        date TEXT,
        due_date TEXT,
        subtotal REAL NOT NULL DEFAULT 0,
        discount_amount REAL NOT NULL DEFAULT 0,
        discount_total REAL NOT NULL DEFAULT 0,
        taxable_amount REAL NOT NULL DEFAULT 0,
        tax_amount REAL NOT NULL DEFAULT 0,
        tax_total REAL NOT NULL DEFAULT 0,
        total_amount REAL NOT NULL DEFAULT 0,
        grand_total REAL NOT NULL DEFAULT 0,
        total REAL NOT NULL DEFAULT 0,
        paid_amount REAL NOT NULL DEFAULT 0,
        outstanding_amount REAL NOT NULL DEFAULT 0,
        payment_status TEXT NOT NULL DEFAULT 'unpaid',
        status TEXT NOT NULL DEFAULT 'unpaid',
        payment_method TEXT DEFAULT 'cash',
        notes TEXT,
        shipping_code TEXT,
        courier_name TEXT,
        tracking_number TEXT,
        offline_client_id TEXT,
        ${commonSyncColumns},
        UNIQUE (organization_id, invoice_number)
      )`,
      `CREATE TABLE IF NOT EXISTS sales_invoice_items (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        invoice_id TEXT NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
        product_id TEXT REFERENCES products(id) ON DELETE SET NULL,
        product_name TEXT,
        description TEXT,
        hsn_code TEXT,
        quantity REAL NOT NULL DEFAULT 0 CHECK (quantity >= 0),
        unit_price REAL NOT NULL DEFAULT 0,
        tax_percent REAL NOT NULL DEFAULT 0,
        discount_percent REAL NOT NULL DEFAULT 0,
        line_total REAL NOT NULL DEFAULT 0,
        gst_amount REAL NOT NULL DEFAULT 0,
        cgst_amount REAL NOT NULL DEFAULT 0,
        sgst_amount REAL NOT NULL DEFAULT 0,
        igst_amount REAL NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        sync_status TEXT NOT NULL DEFAULT 'synced',
        offline_local_id TEXT,
        server_id TEXT,
        last_synced_at TEXT,
        deleted_at TEXT
      )`,
      `CREATE TABLE IF NOT EXISTS purchase_invoices (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        supplier_id TEXT REFERENCES suppliers(id) ON DELETE SET NULL,
        supplier_name TEXT,
        invoice_kind TEXT NOT NULL DEFAULT 'purchase_invoice',
        purchase_order_id TEXT,
        return_against_id TEXT,
        goods_received_id TEXT,
        bill_number TEXT NOT NULL,
        bill_date TEXT NOT NULL DEFAULT (date('now')),
        due_date TEXT,
        subtotal REAL NOT NULL DEFAULT 0,
        discount_total REAL NOT NULL DEFAULT 0,
        taxable_amount REAL NOT NULL DEFAULT 0,
        tax_total REAL NOT NULL DEFAULT 0,
        grand_total REAL NOT NULL DEFAULT 0,
        received_status TEXT NOT NULL DEFAULT 'received',
        paid_amount REAL NOT NULL DEFAULT 0,
        outstanding_amount REAL NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'unpaid',
        notes TEXT,
        ${commonSyncColumns},
        UNIQUE (organization_id, bill_number)
      )`,
      `CREATE TABLE IF NOT EXISTS purchase_invoice_items (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        purchase_invoice_id TEXT NOT NULL REFERENCES purchase_invoices(id) ON DELETE CASCADE,
        product_id TEXT REFERENCES products(id) ON DELETE SET NULL,
        product_name TEXT,
        warehouse_id TEXT REFERENCES warehouses(id) ON DELETE SET NULL,
        batch_no TEXT,
        expiry_date TEXT,
        quantity REAL NOT NULL DEFAULT 0,
        unit_cost REAL NOT NULL DEFAULT 0,
        tax_percent REAL NOT NULL DEFAULT 0,
        tax_amount REAL NOT NULL DEFAULT 0,
        line_total REAL NOT NULL DEFAULT 0,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS orders (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        order_number TEXT NOT NULL,
        customer_id TEXT REFERENCES customers(id) ON DELETE SET NULL,
        customer_name TEXT,
        customer_phone TEXT,
        customer_address TEXT,
        order_status TEXT,
        status TEXT,
        payment_status TEXT,
        payment_mode TEXT,
        sales_channel TEXT,
        courier_name TEXT,
        courier TEXT,
        tracking_number TEXT,
        total_amount REAL NOT NULL DEFAULT 0,
        grand_total REAL NOT NULL DEFAULT 0,
        total REAL NOT NULL DEFAULT 0,
        ${commonSyncColumns},
        UNIQUE (organization_id, order_number)
      )`,
      `CREATE TABLE IF NOT EXISTS order_items (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
        product_id TEXT REFERENCES products(id) ON DELETE SET NULL,
        product_name TEXT,
        quantity REAL NOT NULL DEFAULT 0,
        unit_price REAL NOT NULL DEFAULT 0,
        total REAL NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        sync_status TEXT NOT NULL DEFAULT 'synced',
        offline_local_id TEXT,
        server_id TEXT,
        last_synced_at TEXT,
        deleted_at TEXT
      )`,
      `CREATE TABLE IF NOT EXISTS quotations (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        customer_id TEXT REFERENCES customers(id) ON DELETE SET NULL,
        quote_number TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'draft',
        valid_until TEXT,
        subtotal REAL NOT NULL DEFAULT 0,
        discount_total REAL NOT NULL DEFAULT 0,
        tax_total REAL NOT NULL DEFAULT 0,
        grand_total REAL NOT NULL DEFAULT 0,
        notes TEXT,
        ${commonSyncColumns},
        UNIQUE (organization_id, quote_number)
      )`,
      `CREATE TABLE IF NOT EXISTS quotation_items (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        quotation_id TEXT NOT NULL REFERENCES quotations(id) ON DELETE CASCADE,
        product_id TEXT REFERENCES products(id) ON DELETE SET NULL,
        description TEXT,
        quantity REAL NOT NULL DEFAULT 0,
        unit_price REAL NOT NULL DEFAULT 0,
        tax_rate REAL NOT NULL DEFAULT 0,
        tax_amount REAL NOT NULL DEFAULT 0,
        line_total REAL NOT NULL DEFAULT 0,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS delivery_challans (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        customer_id TEXT REFERENCES customers(id) ON DELETE SET NULL,
        challan_number TEXT NOT NULL,
        challan_date TEXT NOT NULL DEFAULT (date('now')),
        status TEXT NOT NULL DEFAULT 'draft',
        notes TEXT,
        ${commonSyncColumns},
        UNIQUE (organization_id, challan_number)
      )`,
      `CREATE TABLE IF NOT EXISTS delivery_challan_items (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        challan_id TEXT NOT NULL REFERENCES delivery_challans(id) ON DELETE CASCADE,
        product_id TEXT REFERENCES products(id) ON DELETE SET NULL,
        description TEXT,
        quantity REAL NOT NULL DEFAULT 0,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS credit_notes (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        invoice_id TEXT REFERENCES sales_invoices(id) ON DELETE SET NULL,
        customer_id TEXT REFERENCES customers(id) ON DELETE SET NULL,
        note_number TEXT NOT NULL,
        note_date TEXT NOT NULL DEFAULT (date('now')),
        reason TEXT,
        subtotal REAL NOT NULL DEFAULT 0,
        tax_total REAL NOT NULL DEFAULT 0,
        grand_total REAL NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'open',
        ${commonSyncColumns},
        UNIQUE (organization_id, note_number)
      )`,
      `CREATE TABLE IF NOT EXISTS credit_note_items (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        credit_note_id TEXT NOT NULL REFERENCES credit_notes(id) ON DELETE CASCADE,
        product_id TEXT REFERENCES products(id) ON DELETE SET NULL,
        quantity REAL NOT NULL DEFAULT 0,
        unit_price REAL NOT NULL DEFAULT 0,
        tax_amount REAL NOT NULL DEFAULT 0,
        line_total REAL NOT NULL DEFAULT 0,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS debit_notes (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        supplier_id TEXT REFERENCES suppliers(id) ON DELETE SET NULL,
        note_number TEXT NOT NULL,
        note_date TEXT NOT NULL DEFAULT (date('now')),
        reason TEXT,
        subtotal REAL NOT NULL DEFAULT 0,
        tax_total REAL NOT NULL DEFAULT 0,
        grand_total REAL NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'open',
        ${commonSyncColumns},
        UNIQUE (organization_id, note_number)
      )`,
      `CREATE TABLE IF NOT EXISTS debit_note_items (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        debit_note_id TEXT NOT NULL REFERENCES debit_notes(id) ON DELETE CASCADE,
        product_id TEXT REFERENCES products(id) ON DELETE SET NULL,
        quantity REAL NOT NULL DEFAULT 0,
        unit_price REAL NOT NULL DEFAULT 0,
        tax_amount REAL NOT NULL DEFAULT 0,
        line_total REAL NOT NULL DEFAULT 0,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS expenses (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        supplier_id TEXT REFERENCES suppliers(id) ON DELETE SET NULL,
        category TEXT,
        description TEXT,
        amount REAL NOT NULL DEFAULT 0,
        tax_amount REAL NOT NULL DEFAULT 0,
        expense_date TEXT NOT NULL DEFAULT (date('now')),
        payment_status TEXT NOT NULL DEFAULT 'paid',
        paid_amount REAL NOT NULL DEFAULT 0,
        outstanding_amount REAL NOT NULL DEFAULT 0,
        payment_method TEXT,
        reference_no TEXT,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS payments (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        party_type TEXT NOT NULL,
        party_id TEXT,
        document_type TEXT,
        document_id TEXT,
        amount REAL NOT NULL DEFAULT 0 CHECK (amount >= 0),
        direction TEXT,
        payment_method TEXT,
        reference_no TEXT,
        payment_date TEXT NOT NULL DEFAULT (date('now')),
        cleared_at TEXT,
        notes TEXT,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS payment_receipts (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        customer_id TEXT REFERENCES customers(id) ON DELETE SET NULL,
        invoice_id TEXT REFERENCES sales_invoices(id) ON DELETE SET NULL,
        receipt_number TEXT,
        receipt_type TEXT,
        amount REAL NOT NULL CHECK (amount > 0),
        payment_method TEXT,
        reference_no TEXT,
        received_at TEXT NOT NULL DEFAULT (datetime('now')),
        notes TEXT,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS ledger_entries (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        account_type TEXT NOT NULL,
        account_id TEXT,
        document_type TEXT NOT NULL,
        document_id TEXT,
        entry_date TEXT NOT NULL DEFAULT (date('now')),
        debit REAL NOT NULL DEFAULT 0,
        credit REAL NOT NULL DEFAULT 0,
        currency TEXT NOT NULL DEFAULT 'INR',
        description TEXT,
        ${commonSyncColumns},
        CHECK (debit >= 0 AND credit >= 0)
      )`,
      `CREATE TABLE IF NOT EXISTS gst_tax_rates (
        id TEXT PRIMARY KEY,
        organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE,
        rate REAL NOT NULL,
        label TEXT,
        hsn_code TEXT,
        is_active INTEGER NOT NULL DEFAULT 1,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now'))
      )`,
      `CREATE TABLE IF NOT EXISTS gst_invoice_summary (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        invoice_id TEXT NOT NULL REFERENCES sales_invoices(id) ON DELETE CASCADE,
        gst_rate REAL NOT NULL DEFAULT 0,
        taxable_amount REAL NOT NULL DEFAULT 0,
        cgst_amount REAL NOT NULL DEFAULT 0,
        sgst_amount REAL NOT NULL DEFAULT 0,
        igst_amount REAL NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE (invoice_id, gst_rate)
      )`,
      `CREATE TABLE IF NOT EXISTS gst_hsn_summary (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        period_key TEXT NOT NULL,
        hsn_code TEXT NOT NULL,
        quantity REAL NOT NULL DEFAULT 0,
        taxable_amount REAL NOT NULL DEFAULT 0,
        tax_amount REAL NOT NULL DEFAULT 0,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        UNIQUE (organization_id, period_key, hsn_code)
      )`,
      `CREATE TABLE IF NOT EXISTS print_templates (
        id TEXT PRIMARY KEY,
        organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE,
        template_key TEXT NOT NULL,
        format TEXT NOT NULL,
        name TEXT NOT NULL,
        is_default INTEGER NOT NULL DEFAULT 0,
        paper_width TEXT,
        font_size REAL,
        show_hsn INTEGER,
        show_tax_breakup INTEGER,
        show_signature INTEGER,
        show_qr INTEGER,
        show_barcode INTEGER,
        pharma_mode INTEGER,
        ${commonSyncColumns},
        UNIQUE (organization_id, template_key)
      )`,
      `CREATE TABLE IF NOT EXISTS license_state (
        id TEXT PRIMARY KEY,
        organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE,
        license_key TEXT,
        customer_id TEXT,
        business_id TEXT,
        business_name TEXT,
        device_id TEXT,
        plan_code TEXT,
        plan_name TEXT,
        status TEXT NOT NULL DEFAULT 'trial',
        expiry_date TEXT,
        grace_period_days INTEGER NOT NULL DEFAULT 0,
        allowed_features TEXT,
        issued_by_admin TEXT,
        notes TEXT,
        issued_at TEXT,
        expires_at TEXT,
        grace_until TEXT,
        last_verified_at TEXT,
        signature TEXT,
        device_limit INTEGER,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS device_activations (
        id TEXT PRIMARY KEY,
        organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE,
        license_id TEXT REFERENCES license_state(id) ON DELETE CASCADE,
        device_id TEXT NOT NULL,
        device_name TEXT,
        platform TEXT,
        activated_at TEXT NOT NULL DEFAULT (datetime('now')),
        last_seen_at TEXT,
        is_active INTEGER NOT NULL DEFAULT 1,
        ${commonSyncColumns},
        UNIQUE (license_id, device_id)
      )`,
      `CREATE TABLE IF NOT EXISTS local_audit_logs (
        id TEXT PRIMARY KEY,
        organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE,
        user_id TEXT,
        action TEXT NOT NULL,
        entity_type TEXT,
        entity_id TEXT,
        description TEXT,
        previous_hash TEXT,
        hash TEXT,
        sync_status TEXT NOT NULL DEFAULT 'synced',
        offline_local_id TEXT,
        server_id TEXT,
        last_synced_at TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        updated_at TEXT NOT NULL DEFAULT (datetime('now')),
        deleted_at TEXT
      )`,
      `CREATE TABLE IF NOT EXISTS backup_manifest (
        id TEXT PRIMARY KEY,
        organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE,
        backup_name TEXT NOT NULL,
        storage_path TEXT,
        checksum TEXT,
        size_bytes INTEGER,
        table_count INTEGER,
        row_count INTEGER,
        verification_status TEXT,
        verified_at TEXT,
        integrity_report TEXT,
        created_at TEXT NOT NULL DEFAULT (datetime('now')),
        restored_at TEXT
      )`,
      `CREATE TABLE IF NOT EXISTS offline_sync_queue (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        entity_type TEXT NOT NULL,
        operation_type TEXT NOT NULL,
        status TEXT NOT NULL DEFAULT 'pending',
        attempts INTEGER NOT NULL DEFAULT 0,
        error TEXT,
        idempotency_key TEXT,
        created_at TEXT NOT NULL,
        updated_at TEXT NOT NULL,
        last_synced_at TEXT
      )`,
      `CREATE TABLE IF NOT EXISTS offline_sync_action_fields (
        action_id TEXT NOT NULL REFERENCES offline_sync_queue(id) ON DELETE CASCADE,
        field_path TEXT NOT NULL,
        value_text TEXT,
        value_number REAL,
        value_boolean INTEGER,
        value_type TEXT NOT NULL,
        PRIMARY KEY (action_id, field_path)
      )`,
      `CREATE TABLE IF NOT EXISTS offline_sync_conflicts (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        entity_type TEXT NOT NULL,
        local_id TEXT,
        server_id TEXT,
        message TEXT NOT NULL,
        resolution TEXT,
        created_at TEXT NOT NULL,
        resolved_at TEXT
      )`,
      `CREATE TABLE IF NOT EXISTS offline_sync_conflict_fields (
        conflict_id TEXT NOT NULL REFERENCES offline_sync_conflicts(id) ON DELETE CASCADE,
        field_path TEXT NOT NULL,
        value_text TEXT,
        value_number REAL,
        value_boolean INTEGER,
        value_type TEXT NOT NULL,
        PRIMARY KEY (conflict_id, field_path)
      )`,
      `CREATE TABLE IF NOT EXISTS offline_sync_logs (
        id TEXT PRIMARY KEY,
        organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE,
        action_id TEXT REFERENCES offline_sync_queue(id) ON DELETE SET NULL,
        status TEXT NOT NULL,
        message TEXT,
        created_at TEXT NOT NULL
      )`,
      `CREATE TABLE IF NOT EXISTS offline_sync_log_fields (
        log_id TEXT NOT NULL REFERENCES offline_sync_logs(id) ON DELETE CASCADE,
        field_path TEXT NOT NULL,
        value_text TEXT,
        value_number REAL,
        value_boolean INTEGER,
        value_type TEXT NOT NULL,
        PRIMARY KEY (log_id, field_path)
      )`,
    ],
  },
  {
    version: 2,
    name: "offline_erp_performance_indexes",
    sql: [
      "CREATE INDEX IF NOT EXISTS idx_products_org_name ON products (organization_id, name COLLATE NOCASE)",
      "CREATE INDEX IF NOT EXISTS idx_products_org_sku ON products (organization_id, sku)",
      "CREATE INDEX IF NOT EXISTS idx_products_org_barcode ON products (organization_id, barcode)",
      "CREATE INDEX IF NOT EXISTS idx_products_org_stock ON products (organization_id, stock, min_stock)",
      "CREATE INDEX IF NOT EXISTS idx_products_org_deleted ON products (organization_id, deleted_at)",
      "CREATE INDEX IF NOT EXISTS idx_customers_org_name ON customers (organization_id, name COLLATE NOCASE)",
      "CREATE INDEX IF NOT EXISTS idx_customers_org_phone ON customers (organization_id, phone)",
      "CREATE INDEX IF NOT EXISTS idx_suppliers_org_name ON suppliers (organization_id, name COLLATE NOCASE)",
      "CREATE INDEX IF NOT EXISTS idx_inventory_product_warehouse ON inventory_items (organization_id, product_id, warehouse_id)",
      "CREATE INDEX IF NOT EXISTS idx_batches_product_expiry ON stock_batches (organization_id, product_id, expiry_date)",
      "CREATE INDEX IF NOT EXISTS idx_movements_org_product_date ON stock_movements (organization_id, product_id, datetime(created_at) DESC)",
      "CREATE INDEX IF NOT EXISTS idx_movements_org_ref ON stock_movements (organization_id, reference_no)",
      "CREATE INDEX IF NOT EXISTS idx_sales_invoices_org_created ON sales_invoices (organization_id, datetime(created_at) DESC)",
      "CREATE INDEX IF NOT EXISTS idx_sales_invoices_org_number ON sales_invoices (organization_id, invoice_number)",
      "CREATE INDEX IF NOT EXISTS idx_sales_invoices_org_customer ON sales_invoices (organization_id, customer_id, datetime(created_at) DESC)",
      "CREATE INDEX IF NOT EXISTS idx_sales_invoices_org_status ON sales_invoices (organization_id, payment_status, datetime(created_at) DESC)",
      "CREATE INDEX IF NOT EXISTS idx_sales_items_invoice ON sales_invoice_items (organization_id, invoice_id)",
      "CREATE INDEX IF NOT EXISTS idx_sales_items_product ON sales_invoice_items (organization_id, product_id)",
      "CREATE INDEX IF NOT EXISTS idx_purchase_invoices_org_created ON purchase_invoices (organization_id, datetime(created_at) DESC)",
      "CREATE INDEX IF NOT EXISTS idx_orders_org_created ON orders (organization_id, datetime(created_at) DESC)",
      "CREATE INDEX IF NOT EXISTS idx_orders_org_number ON orders (organization_id, order_number)",
      "CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items (organization_id, order_id)",
      "CREATE INDEX IF NOT EXISTS idx_ledger_org_date ON ledger_entries (organization_id, entry_date DESC)",
      "CREATE INDEX IF NOT EXISTS idx_ledger_org_account ON ledger_entries (organization_id, account_type, account_id)",
      "CREATE INDEX IF NOT EXISTS idx_expenses_org_date ON expenses (organization_id, expense_date DESC)",
      "CREATE INDEX IF NOT EXISTS idx_receipts_org_invoice ON payment_receipts (organization_id, invoice_id)",
      "CREATE INDEX IF NOT EXISTS idx_audit_org_created ON local_audit_logs (organization_id, datetime(created_at) DESC)",
      "CREATE INDEX IF NOT EXISTS idx_sync_queue_status ON offline_sync_queue (status, datetime(created_at))",
      "CREATE INDEX IF NOT EXISTS idx_sync_queue_org ON offline_sync_queue (organization_id, status)",
      "CREATE INDEX IF NOT EXISTS idx_backup_org_created ON backup_manifest (organization_id, datetime(created_at) DESC)",
    ],
  },
  {
    version: 3,
    name: "offline_erp_sync_column_completion",
    sql: [
      "ALTER TABLE local_users ADD COLUMN organization_id TEXT REFERENCES organizations(id) ON DELETE CASCADE",
      "ALTER TABLE sales_invoices ADD COLUMN offline_client_id TEXT",
      "ALTER TABLE purchase_invoice_items ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'synced'",
      "ALTER TABLE purchase_invoice_items ADD COLUMN offline_local_id TEXT",
      "ALTER TABLE purchase_invoice_items ADD COLUMN server_id TEXT",
      "ALTER TABLE purchase_invoice_items ADD COLUMN last_synced_at TEXT",
      "ALTER TABLE purchase_invoice_items ADD COLUMN deleted_at TEXT",
      "ALTER TABLE quotation_items ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'synced'",
      "ALTER TABLE quotation_items ADD COLUMN offline_local_id TEXT",
      "ALTER TABLE quotation_items ADD COLUMN server_id TEXT",
      "ALTER TABLE quotation_items ADD COLUMN last_synced_at TEXT",
      "ALTER TABLE quotation_items ADD COLUMN deleted_at TEXT",
      "ALTER TABLE delivery_challan_items ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'synced'",
      "ALTER TABLE delivery_challan_items ADD COLUMN offline_local_id TEXT",
      "ALTER TABLE delivery_challan_items ADD COLUMN server_id TEXT",
      "ALTER TABLE delivery_challan_items ADD COLUMN last_synced_at TEXT",
      "ALTER TABLE delivery_challan_items ADD COLUMN deleted_at TEXT",
      "ALTER TABLE credit_note_items ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'synced'",
      "ALTER TABLE credit_note_items ADD COLUMN offline_local_id TEXT",
      "ALTER TABLE credit_note_items ADD COLUMN server_id TEXT",
      "ALTER TABLE credit_note_items ADD COLUMN last_synced_at TEXT",
      "ALTER TABLE credit_note_items ADD COLUMN deleted_at TEXT",
      "ALTER TABLE debit_note_items ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'synced'",
      "ALTER TABLE debit_note_items ADD COLUMN offline_local_id TEXT",
      "ALTER TABLE debit_note_items ADD COLUMN server_id TEXT",
      "ALTER TABLE debit_note_items ADD COLUMN last_synced_at TEXT",
      "ALTER TABLE debit_note_items ADD COLUMN deleted_at TEXT",
      "ALTER TABLE license_state ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'synced'",
      "ALTER TABLE license_state ADD COLUMN offline_local_id TEXT",
      "ALTER TABLE license_state ADD COLUMN server_id TEXT",
      "ALTER TABLE license_state ADD COLUMN last_synced_at TEXT",
      "ALTER TABLE license_state ADD COLUMN created_at TEXT",
      "ALTER TABLE license_state ADD COLUMN deleted_at TEXT",
      "ALTER TABLE device_activations ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'synced'",
      "ALTER TABLE device_activations ADD COLUMN offline_local_id TEXT",
      "ALTER TABLE device_activations ADD COLUMN server_id TEXT",
      "ALTER TABLE device_activations ADD COLUMN last_synced_at TEXT",
      "ALTER TABLE device_activations ADD COLUMN created_at TEXT",
      "ALTER TABLE device_activations ADD COLUMN updated_at TEXT",
      "ALTER TABLE device_activations ADD COLUMN deleted_at TEXT",
      "ALTER TABLE local_audit_logs ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'synced'",
      "ALTER TABLE local_audit_logs ADD COLUMN offline_local_id TEXT",
      "ALTER TABLE local_audit_logs ADD COLUMN server_id TEXT",
      "ALTER TABLE local_audit_logs ADD COLUMN last_synced_at TEXT",
      "ALTER TABLE local_audit_logs ADD COLUMN updated_at TEXT",
      "ALTER TABLE local_audit_logs ADD COLUMN deleted_at TEXT",
      "ALTER TABLE print_templates ADD COLUMN sync_status TEXT NOT NULL DEFAULT 'synced'",
      "ALTER TABLE print_templates ADD COLUMN offline_local_id TEXT",
      "ALTER TABLE print_templates ADD COLUMN server_id TEXT",
      "ALTER TABLE print_templates ADD COLUMN last_synced_at TEXT",
      "ALTER TABLE print_templates ADD COLUMN created_at TEXT",
      "ALTER TABLE print_templates ADD COLUMN deleted_at TEXT",
      "CREATE INDEX IF NOT EXISTS idx_purchase_items_invoice ON purchase_invoice_items (organization_id, purchase_invoice_id)",
      "CREATE INDEX IF NOT EXISTS idx_purchase_items_product ON purchase_invoice_items (organization_id, product_id)",
      "CREATE INDEX IF NOT EXISTS idx_payments_org_document ON payments (organization_id, document_type, document_id)",
      "CREATE INDEX IF NOT EXISTS idx_quotations_org_created ON quotations (organization_id, datetime(created_at) DESC)",
      "CREATE INDEX IF NOT EXISTS idx_challans_org_created ON delivery_challans (organization_id, datetime(created_at) DESC)",
      "CREATE INDEX IF NOT EXISTS idx_credit_notes_org_created ON credit_notes (organization_id, datetime(created_at) DESC)",
      "CREATE INDEX IF NOT EXISTS idx_debit_notes_org_created ON debit_notes (organization_id, datetime(created_at) DESC)",
      "CREATE INDEX IF NOT EXISTS idx_license_org_status ON license_state (organization_id, status)",
    ],
  },
  {
    version: 4,
    name: "professional_offline_erp_completion",
    sql: [
      "ALTER TABLE sales_invoices ADD COLUMN paid_amount REAL NOT NULL DEFAULT 0",
      "ALTER TABLE sales_invoices ADD COLUMN outstanding_amount REAL NOT NULL DEFAULT 0",
      "ALTER TABLE purchase_invoices ADD COLUMN invoice_kind TEXT NOT NULL DEFAULT 'purchase_invoice'",
      "ALTER TABLE purchase_invoices ADD COLUMN purchase_order_id TEXT",
      "ALTER TABLE purchase_invoices ADD COLUMN return_against_id TEXT",
      "ALTER TABLE purchase_invoices ADD COLUMN goods_received_id TEXT",
      "ALTER TABLE purchase_invoices ADD COLUMN received_status TEXT NOT NULL DEFAULT 'received'",
      "ALTER TABLE purchase_invoices ADD COLUMN paid_amount REAL NOT NULL DEFAULT 0",
      "ALTER TABLE purchase_invoices ADD COLUMN outstanding_amount REAL NOT NULL DEFAULT 0",
      "ALTER TABLE purchase_invoice_items ADD COLUMN warehouse_id TEXT REFERENCES warehouses(id) ON DELETE SET NULL",
      "ALTER TABLE purchase_invoice_items ADD COLUMN batch_no TEXT",
      "ALTER TABLE purchase_invoice_items ADD COLUMN expiry_date TEXT",
      "ALTER TABLE payments ADD COLUMN direction TEXT",
      "ALTER TABLE payments ADD COLUMN cleared_at TEXT",
      "ALTER TABLE payment_receipts ADD COLUMN receipt_type TEXT",
      "ALTER TABLE expenses ADD COLUMN payment_status TEXT NOT NULL DEFAULT 'paid'",
      "ALTER TABLE expenses ADD COLUMN paid_amount REAL NOT NULL DEFAULT 0",
      "ALTER TABLE expenses ADD COLUMN outstanding_amount REAL NOT NULL DEFAULT 0",
      "ALTER TABLE backup_manifest ADD COLUMN verification_status TEXT",
      "ALTER TABLE backup_manifest ADD COLUMN verified_at TEXT",
      "ALTER TABLE backup_manifest ADD COLUMN integrity_report TEXT",
      "CREATE INDEX IF NOT EXISTS idx_sales_report_org_date ON sales_invoices (organization_id, invoice_date DESC, payment_status)",
      "CREATE INDEX IF NOT EXISTS idx_sales_outstanding ON sales_invoices (organization_id, outstanding_amount, customer_id)",
      "CREATE INDEX IF NOT EXISTS idx_purchase_report_org_date ON purchase_invoices (organization_id, bill_date DESC, invoice_kind, status)",
      "CREATE INDEX IF NOT EXISTS idx_purchase_outstanding ON purchase_invoices (organization_id, outstanding_amount, supplier_id)",
      "CREATE INDEX IF NOT EXISTS idx_expense_report_org_category_date ON expenses (organization_id, category, expense_date DESC)",
      "CREATE INDEX IF NOT EXISTS idx_payments_org_party_date ON payments (organization_id, party_type, party_id, payment_date DESC)",
      "CREATE INDEX IF NOT EXISTS idx_receipts_org_customer_date ON payment_receipts (organization_id, customer_id, received_at DESC)",
      "CREATE INDEX IF NOT EXISTS idx_stock_movements_org_type_date ON stock_movements (organization_id, type, movement_date DESC)",
      "CREATE INDEX IF NOT EXISTS idx_ledger_org_doc ON ledger_entries (organization_id, document_type, document_id)",
      "CREATE INDEX IF NOT EXISTS idx_ledger_org_doc_account ON ledger_entries (organization_id, document_type, document_id, account_type, account_id)",
      "CREATE INDEX IF NOT EXISTS idx_gst_invoice_summary_org_rate ON gst_invoice_summary (organization_id, gst_rate)",
      "CREATE INDEX IF NOT EXISTS idx_backup_verification ON backup_manifest (organization_id, verification_status, verified_at)",
    ],
  },
  {
    version: 5,
    name: "admin_issued_offline_license_activation",
    sql: [
      "ALTER TABLE license_state ADD COLUMN customer_id TEXT",
      "ALTER TABLE license_state ADD COLUMN business_id TEXT",
      "ALTER TABLE license_state ADD COLUMN business_name TEXT",
      "ALTER TABLE license_state ADD COLUMN device_id TEXT",
      "ALTER TABLE license_state ADD COLUMN plan_name TEXT",
      "ALTER TABLE license_state ADD COLUMN expiry_date TEXT",
      "ALTER TABLE license_state ADD COLUMN grace_period_days INTEGER NOT NULL DEFAULT 0",
      "ALTER TABLE license_state ADD COLUMN allowed_features TEXT",
      "ALTER TABLE license_state ADD COLUMN issued_by_admin TEXT",
      "ALTER TABLE license_state ADD COLUMN notes TEXT",
      "CREATE INDEX IF NOT EXISTS idx_license_org_device_status ON license_state (organization_id, device_id, status)",
      "CREATE INDEX IF NOT EXISTS idx_license_org_expiry ON license_state (organization_id, expiry_date, grace_until)",
      "CREATE INDEX IF NOT EXISTS idx_device_activation_device ON device_activations (device_id, is_active)",
    ],
  },
  {
    version: 6,
    name: "international_accounting_and_reporting_completion",
    sql: [
      `CREATE TABLE IF NOT EXISTS chart_of_accounts (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        account_code TEXT NOT NULL,
        account_name TEXT NOT NULL,
        account_type TEXT NOT NULL,
        account_group TEXT,
        parent_id TEXT REFERENCES chart_of_accounts(id) ON DELETE SET NULL,
        normal_balance TEXT NOT NULL DEFAULT 'debit',
        opening_balance REAL NOT NULL DEFAULT 0,
        current_balance REAL NOT NULL DEFAULT 0,
        is_system INTEGER NOT NULL DEFAULT 0,
        is_cash_account INTEGER NOT NULL DEFAULT 0,
        is_bank_account INTEGER NOT NULL DEFAULT 0,
        is_active INTEGER NOT NULL DEFAULT 1,
        notes TEXT,
        ${commonSyncColumns},
        UNIQUE (organization_id, account_code),
        UNIQUE (organization_id, account_name)
      )`,
      `CREATE TABLE IF NOT EXISTS bank_accounts (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        account_id TEXT REFERENCES chart_of_accounts(id) ON DELETE SET NULL,
        bank_name TEXT NOT NULL,
        branch_name TEXT,
        account_number TEXT,
        ifsc_code TEXT,
        account_holder TEXT,
        opening_balance REAL NOT NULL DEFAULT 0,
        current_balance REAL NOT NULL DEFAULT 0,
        is_active INTEGER NOT NULL DEFAULT 1,
        notes TEXT,
        ${commonSyncColumns}
      )`,
      `CREATE TABLE IF NOT EXISTS accounting_vouchers (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        voucher_number TEXT NOT NULL,
        voucher_type TEXT NOT NULL,
        voucher_date TEXT NOT NULL DEFAULT (date('now')),
        reference_no TEXT,
        narration TEXT,
        total_debit REAL NOT NULL DEFAULT 0,
        total_credit REAL NOT NULL DEFAULT 0,
        status TEXT NOT NULL DEFAULT 'posted',
        ${commonSyncColumns},
        UNIQUE (organization_id, voucher_number)
      )`,
      `CREATE TABLE IF NOT EXISTS accounting_voucher_entries (
        id TEXT PRIMARY KEY,
        organization_id TEXT NOT NULL REFERENCES organizations(id) ON DELETE CASCADE,
        voucher_id TEXT NOT NULL REFERENCES accounting_vouchers(id) ON DELETE CASCADE,
        account_id TEXT REFERENCES chart_of_accounts(id) ON DELETE SET NULL,
        account_type TEXT NOT NULL,
        party_type TEXT,
        party_id TEXT,
        line_no INTEGER NOT NULL DEFAULT 1,
        debit REAL NOT NULL DEFAULT 0,
        credit REAL NOT NULL DEFAULT 0,
        description TEXT,
        ${commonSyncColumns},
        CHECK (debit >= 0 AND credit >= 0)
      )`,
      "CREATE INDEX IF NOT EXISTS idx_chart_accounts_org_type ON chart_of_accounts (organization_id, account_type, is_active)",
      "CREATE INDEX IF NOT EXISTS idx_chart_accounts_org_group ON chart_of_accounts (organization_id, account_group, account_name COLLATE NOCASE)",
      "CREATE INDEX IF NOT EXISTS idx_bank_accounts_org_active ON bank_accounts (organization_id, is_active)",
      "CREATE INDEX IF NOT EXISTS idx_vouchers_org_date_type ON accounting_vouchers (organization_id, voucher_date DESC, voucher_type)",
      "CREATE INDEX IF NOT EXISTS idx_voucher_entries_voucher ON accounting_voucher_entries (organization_id, voucher_id, line_no)",
      "CREATE INDEX IF NOT EXISTS idx_voucher_entries_account ON accounting_voucher_entries (organization_id, account_id)",
      "CREATE INDEX IF NOT EXISTS idx_ledger_org_account_date ON ledger_entries (organization_id, account_type, account_id, entry_date DESC)",
      "CREATE INDEX IF NOT EXISTS idx_sales_items_hsn ON sales_invoice_items (organization_id, hsn_code, tax_percent)",
      "CREATE INDEX IF NOT EXISTS idx_purchase_items_hsn ON purchase_invoice_items (organization_id, product_id, tax_percent)",
      "CREATE INDEX IF NOT EXISTS idx_stock_batches_barcode ON stock_batches (organization_id, barcode)",
    ],
  },
]
