import Link from "next/link"
import { findPublicInvoiceShare } from "@/lib/server/invoice-share"

export const dynamic = "force-dynamic"

type PageProps = {
  params: Promise<{ token: string }>
}

export default async function SharedInvoicePage({ params }: PageProps) {
  const { token } = await params
  const share = await findPublicInvoiceShare(token)
  if (!share || share.document_type !== "invoice") {
    return (
      <main className="flex min-h-dvh items-center justify-center bg-slate-100 px-5 text-slate-950">
        <section className="w-full max-w-lg rounded-3xl border border-slate-200 bg-white p-8 text-center shadow-xl">
          <p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-700">Bezgrow Invoice</p>
          <h1 className="mt-4 text-3xl font-black">This invoice link is unavailable.</h1>
          <p className="mt-3 text-sm leading-6 text-slate-600">It may have expired or been revoked. Ask the issuing business for a new link.</p>
        </section>
      </main>
    )
  }

  const pdfPath = `/api/public/invoice-shares/${encodeURIComponent(token)}/pdf`
  return (
    <main className="min-h-dvh bg-slate-100 px-3 py-5 text-slate-950 sm:px-6">
      <section className="mx-auto max-w-5xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl">
        <header className="flex flex-col gap-5 border-b border-slate-200 px-5 py-6 sm:flex-row sm:items-center sm:justify-between sm:px-8">
          <div>
            <p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-700">{share.business_name}</p>
            <h1 className="mt-2 text-3xl font-black">Invoice {share.invoice_number}</h1>
            <p className="mt-2 text-sm text-slate-600">Issued to {share.customer_name}</p>
            <p className="mt-1 text-xs text-slate-500">Available until {new Date(share.expires_at).toLocaleDateString("en-IN")}</p>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <Link href={pdfPath} target="_blank" className="rounded-xl bg-slate-950 px-5 py-3 text-center text-sm font-black text-white">
              View PDF
            </Link>
            <Link href={`${pdfPath}?download=1`} className="rounded-xl border border-slate-300 px-5 py-3 text-center text-sm font-black text-slate-950">
              Download PDF
            </Link>
          </div>
        </header>
        <div className="bg-slate-200 p-2 sm:p-5">
          <iframe
            title={`Invoice ${share.invoice_number}`}
            src={pdfPath}
            className="h-[72dvh] min-h-[560px] w-full rounded-xl bg-white"
          />
        </div>
        <footer className="px-5 py-5 text-center">
          <p className="font-black text-slate-800">Thank you</p>
          <p className="mt-1 text-xs text-slate-500">Generated by Bezgrow</p>
        </footer>
      </section>
    </main>
  )
}
