import Link from "next/link"
import { findPublicInvoiceShare } from "@/lib/server/invoice-share"

export const dynamic = "force-dynamic"

type PageProps = { params: Promise<{ token: string }> }

export default async function SharedReportPage({ params }: PageProps) {
  const { token } = await params
  const share = await findPublicInvoiceShare(token)
  if (!share || share.document_type !== "report") {
    return <main className="grid min-h-dvh place-items-center bg-slate-100 p-6 text-center text-slate-950"><div><h1 className="text-3xl font-black">This report link is unavailable.</h1><p className="mt-3 text-slate-600">It may have expired or been revoked.</p></div></main>
  }
  const pdfPath = `/api/public/invoice-shares/${encodeURIComponent(token)}/pdf`
  return (
    <main className="min-h-dvh bg-slate-100 p-3 text-slate-950 sm:p-6">
      <section className="mx-auto max-w-6xl overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-xl">
        <header className="flex flex-col gap-5 border-b border-slate-200 p-5 sm:flex-row sm:items-center sm:justify-between sm:p-8">
          <div>
            <p className="text-xs font-black uppercase tracking-[0.2em] text-cyan-700">{share.business_name}</p>
            <h1 className="mt-2 text-3xl font-black">{share.title}</h1>
            <p className="mt-2 text-sm text-slate-600">{share.period}</p>
            <p className="mt-1 text-xs text-slate-500">Available until {new Date(share.expires_at).toLocaleDateString("en-IN")}</p>
          </div>
          <div className="grid grid-cols-2 gap-3">
            <Link href={pdfPath} target="_blank" className="rounded-xl bg-slate-950 px-5 py-3 text-center text-sm font-black text-white">View PDF</Link>
            <Link href={`${pdfPath}?download=1`} className="rounded-xl border border-slate-300 px-5 py-3 text-center text-sm font-black">Download PDF</Link>
          </div>
        </header>
        <div className="bg-slate-200 p-2 sm:p-5">
          <iframe title={share.title} src={pdfPath} className="h-[72dvh] min-h-[560px] w-full rounded-xl bg-white" />
        </div>
        <footer className="p-5 text-center"><p className="font-black">Thank you</p><p className="mt-1 text-xs text-slate-500">Generated by Bezgrow</p></footer>
      </section>
    </main>
  )
}
