"use client"

import Barcode from "react-barcode"
import { QRCodeSVG } from "qrcode.react"
import type { PrintInvoice, PrintSettings } from "@/components/print/types"
import { formatDate, formatMoney } from "@/components/print/utils"
import { BusinessLogo } from "./PrintBlocks"

function joinFilled(parts: string[]) {
  return parts.filter((part) => part.trim() && !part.endsWith(": -")).join(" | ")
}

export function ThermalTemplate({ invoice, settings }: { invoice: PrintInvoice; settings: PrintSettings }) {
  const businessDetails = joinFilled([
    `GST: ${invoice.enterprise.gstNumber}`,
    `Phone: ${invoice.enterprise.phone}`,
  ])

  return (
    <article className={`invoice-paper print-thermal thermal-${settings.thermalWidth.replace("mm", "")}`}>
      {settings.showWatermark && <div className="watermark thermal-watermark" aria-hidden="true"><span>{invoice.watermark}</span></div>}
      <header className="thermal-center">
        {settings.showLogo && <BusinessLogo invoice={invoice} className="thermal-brand-logo" />}
        <h1>{invoice.enterprise.name}</h1>
        {invoice.enterprise.address !== "-" && <p>{invoice.enterprise.address}</p>}
        {businessDetails && <p>{businessDetails}</p>}
      </header>

      <div className="thermal-rule" />
      <div className="thermal-row"><span>Invoice</span><strong>{invoice.invoiceNumber}</strong></div>
      <div className="thermal-row"><span>Date</span><strong>{formatDate(invoice.invoiceDate)}</strong></div>
      <div className="thermal-row"><span>Customer</span><strong>{invoice.customer.name}</strong></div>
      <div className="thermal-row"><span>Phone</span><strong>{invoice.customer.phone}</strong></div>
      <div className="thermal-row"><span>Payment</span><strong>{invoice.payment.mode}</strong></div>
      <div className="thermal-rule" />

      <table className="thermal-table">
        <thead>
          <tr>
            <th>Item</th>
            <th>Qty</th>
            {settings.showGstDetails && <th>GST</th>}
            <th>Amt</th>
          </tr>
        </thead>
        <tbody>
          {invoice.items.map((item) => (
            <tr key={item.id}>
              <td>
                {item.name}
                {(settings.showHsn || settings.pharmaMode) && (
                  <><br /><span>{settings.showHsn ? item.hsnCode : ""} {settings.pharmaMode && item.batchNumber !== "-" ? `B:${item.batchNumber}` : ""}</span></>
                )}
              </td>
              <td>{item.quantity}</td>
              {settings.showGstDetails && <td>{item.cgstPercent + item.sgstPercent + item.igstPercent}%</td>}
              <td>{formatMoney(item.finalAmount)}</td>
            </tr>
          ))}
        </tbody>
      </table>

      <div className="thermal-rule" />
      <div className="thermal-row"><span>Subtotal</span><strong>{formatMoney(invoice.totals.subtotal)}</strong></div>
      <div className="thermal-row"><span>Discount</span><strong>{formatMoney(invoice.totals.discount)}</strong></div>
      {settings.showGstDetails && <div className="thermal-row"><span>GST</span><strong>{formatMoney(invoice.totals.cgst + invoice.totals.sgst + invoice.totals.igst)}</strong></div>}
      <div className="thermal-total"><span>Total</span><strong>{formatMoney(invoice.totals.grandTotal)}</strong></div>
      <div className="thermal-row"><span>Cash Received</span><strong>{formatMoney(invoice.payment.cashReceived)}</strong></div>
      <div className="thermal-row"><span>Balance</span><strong>{formatMoney(invoice.payment.balanceAmount)}</strong></div>

      {(settings.showBarcode || settings.showQr) && <div className="thermal-rule" />}
      <section className="thermal-codes" aria-label="Invoice reference codes">
        {settings.showBarcode && (
          <figure className="thermal-barcode" data-code-kind="barcode">
            <Barcode value={invoice.barcodeValue} height={38} width={1} displayValue={false} margin={0} />
            <figcaption>{invoice.invoiceNumber}</figcaption>
          </figure>
        )}
        {settings.showQr && (
          <figure className="thermal-qr" data-code-kind="qr">
            <QRCodeSVG value={invoice.qrValue} size={58} marginSize={1} />
            <figcaption>Invoice reference</figcaption>
          </figure>
        )}
      </section>
      {invoice.notes && <p className="thermal-center">{invoice.notes}</p>}
      <footer className="thermal-generated-footer">
        <strong>Thank you</strong>
        <span>Generated by Bezgrow</span>
      </footer>
    </article>
  )
}
