export type InvoiceShareInput = {
  customerName: string
  customerPhone?: string | null
  customerEmail?: string | null
  enterpriseName: string
  invoiceNumber: string
  invoiceDate?: string
  amount: number
  paidAmount?: number
  dueAmount?: number
  secureInvoiceUrl?: string
}

function money(value: number | undefined) {
  return `₹${Number(value || 0).toLocaleString("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`
}

function formattedDate(value: string | undefined) {
  if (!value) return "-"
  const date = new Date(value)
  return Number.isNaN(date.getTime()) ? value : date.toLocaleDateString("en-IN")
}

export function normalizeWhatsAppPhone(phone: string | null | undefined) {
  const raw = String(phone || "").trim()
  if (!raw) return ""
  let digits = raw.replace(/\D/g, "")
  if (digits.startsWith("00")) digits = digits.slice(2)
  if (digits.length === 11 && digits.startsWith("0")) digits = digits.slice(1)

  if (digits.length === 10) {
    return /^[6-9]\d{9}$/.test(digits) ? `91${digits}` : ""
  }
  if (digits.startsWith("91") && digits.length === 12) {
    return /^91[6-9]\d{9}$/.test(digits) ? digits : ""
  }
  if (/^[1-9]\d{7,14}$/.test(digits)) return digits
  return ""
}

export function validateCustomerEmail(email: string | null | undefined) {
  const normalized = String(email || "").trim()
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(normalized) ? normalized : ""
}

export function createInvoiceShareText(input: InvoiceShareInput) {
  const lines = [
    `Hello ${input.customerName || "Customer"},`,
    "",
    `Please find invoice ${input.invoiceNumber || "Invoice"} from ${input.enterpriseName || "our business"}.`,
    "",
    `Invoice total: ${money(input.amount)}`,
    "",
  ]
  if (input.secureInvoiceUrl) {
    lines.push(`View or download the invoice: ${input.secureInvoiceUrl}`, "")
  }
  lines.push("Thank you.", "Generated by Bezgrow")
  return lines.join("\n")
}

export function createWhatsAppInvoiceUrl(input: InvoiceShareInput) {
  const phone = normalizeWhatsAppPhone(input.customerPhone)
  if (!phone) return ""
  return `https://wa.me/${phone}?text=${encodeURIComponent(createInvoiceShareText(input))}`
}

export function createInvoiceEmailDraft(input: InvoiceShareInput) {
  const recipient = validateCustomerEmail(input.customerEmail)
  const subject = `Invoice ${input.invoiceNumber} from ${input.enterpriseName}`
  const body = [
    `Hello ${input.customerName || "Customer"},`,
    "",
    `Please find your invoice from ${input.enterpriseName || "our business"}.`,
    "",
    `Invoice number: ${input.invoiceNumber || "Invoice"}`,
    `Invoice date: ${formattedDate(input.invoiceDate)}`,
    `Grand total: ${money(input.amount)}`,
    `Paid amount: ${money(input.paidAmount)}`,
    `Due amount: ${money(input.dueAmount)}`,
    "",
    input.secureInvoiceUrl
      ? `View or download your invoice:\n${input.secureInvoiceUrl}`
      : "The invoice PDF was prepared locally. Please attach it to this draft before sending.",
    "",
    "Thank you,",
    input.enterpriseName || "our business",
    "Generated by Bezgrow",
  ].join("\n")
  return {
    recipient,
    subject,
    body,
    mailtoUrl: `mailto:${encodeURIComponent(recipient)}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`,
  }
}
