import assert from "node:assert/strict"
import { decodePDFRawStream, PDFArray, PDFDocument, PDFRawStream, PDFStream, type PDFPage } from "pdf-lib"
import { defaultPrintSettings } from "../components/print/settings/defaults"
import type { PrintFormat } from "../components/print/types"
import {
  clearCanonicalInvoiceDocumentCache,
  getCanonicalInvoiceDocument,
  validateCanonicalInvoicePdf,
} from "../lib/invoice-document"
import { invoice } from "./test-invoice-pdf-layout"

async function pdfText(bytes: Uint8Array) {
  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs")
  const standardFontDataUrl = decodeURIComponent(new URL("../node_modules/pdfjs-dist/standard_fonts/", import.meta.url).pathname)
  const loading = pdfjs.getDocument({ data: bytes.slice(), standardFontDataUrl })
  try {
    const document = await loading.promise
    const pages: string[] = []
    for (let pageNumber = 1; pageNumber <= document.numPages; pageNumber += 1) {
      const page = await document.getPage(pageNumber)
      const content = await page.getTextContent()
      pages.push(content.items.map((item) => "str" in item ? item.str : "").join(" "))
    }
    return pages.join("\n")
  } finally {
    await loading.destroy()
  }
}

async function pdfTextPositions(bytes: Uint8Array) {
  const pdfjs = await import("pdfjs-dist/legacy/build/pdf.mjs")
  const loading = pdfjs.getDocument({ data: bytes.slice() })
  try {
    const page = await (await loading.promise).getPage(1)
    const content = await page.getTextContent()
    return content.items.flatMap((item) => "str" in item && item.str.trim()
      ? [{ text: item.str, y: item.transform[5] }]
      : [])
  } finally {
    await loading.destroy()
  }
}

function drawingText(page: PDFPage) {
  const contents = page.node.Contents()
  if (!contents) return ""
  const streams: PDFStream[] = []
  if (contents instanceof PDFStream) streams.push(contents)
  else if (contents instanceof PDFArray) {
    for (let index = 0; index < contents.size(); index += 1) {
      const stream = contents.lookupMaybe(index, PDFStream)
      if (stream) streams.push(stream)
    }
  }
  return streams.map((stream) => {
    try {
      return new TextDecoder("latin1").decode(
        stream instanceof PDFRawStream ? decodePDFRawStream(stream).decode() : stream.getContents(),
      )
    } catch {
      return new TextDecoder("latin1").decode(stream.getContents())
    }
  }).join("\n")
}

async function run() {
  clearCanonicalInvoiceDocumentCache()
  const representative = {
    ...invoice(5, true),
    id: "canonical-invoice",
    invoiceNumber: "INV-00005",
    barcodeValue: "INV00005",
    qrValue: "BEZGROW:INV-00005",
    customer: { ...invoice(5, true).customer, name: "Monika Sharma" },
  }
  const settings = {
    ...defaultPrintSettings,
    showLogo: true,
    showQr: true,
    showBarcode: true,
    showHsn: true,
    showGstDetails: true,
    showSignature: true,
    showWatermark: true,
  }

  const firstRenderStarted = performance.now()
  const promises = [
    getCanonicalInvoiceDocument(representative, settings, "a4"),
    getCanonicalInvoiceDocument(representative, settings, "a4"),
  ] as const
  assert.strictEqual(promises[0], promises[1], "Identical PDF requests must share one in-flight render")
  const [a4, cachedA4] = await Promise.all(promises)
  const firstRenderMs = performance.now() - firstRenderStarted
  assert.strictEqual(a4, cachedA4, "Preview, Save, Print, and Share must reuse the same artifact object")
  const cachedRenderStarted = performance.now()
  assert.strictEqual(await getCanonicalInvoiceDocument(representative, settings, "a4"), a4)
  const cachedRenderMs = performance.now() - cachedRenderStarted
  assert.equal(new TextDecoder().decode(a4.bytes.slice(0, 5)), "%PDF-")
  assert.ok(a4.bytes.byteLength > 5_000)
  assert.equal(a4.pageCount, 1)
  assert.ok(a4.pageContentBytes[0] > 1_000, "The canonical A4 first page must contain substantial drawing content")

  const text = (await pdfText(a4.bytes)).replace(/\s+/g, " ")
  assert.match(text, /INV-00005/, "The authoritative PDF must contain the invoice number")
  assert.match(text, /Monika Sharma/, "The authoritative PDF must contain the customer name")
  assert.match(text, /Grand Total/i, "The authoritative PDF must contain the grand total label")
  assert.match(text, /Thank you/, "The authoritative PDF must contain the invoice footer")
  assert.match(text, /Generated by Bezgrow/, "The authoritative PDF must contain the Bezgrow attribution")
  for (const expectedLabel of [
    "GST:", "FSSAI:", "Branch:", "Salesperson:", "State:", "Sr", "HSN", "Qty", "Free",
    "Unit", "MRP", "Rate", "Disc", "Taxable", "CGST", "SGST", "IGST", "Amount",
    "Subtotal", "Discount", "Round Off", "Paid:", "Due:", "Amount in words",
  ]) {
    assert.ok(text.includes(expectedLabel), `Professional A4 field missing: ${expectedLabel}`)
  }

  const formats: PrintFormat[] = ["a4", "half-compact", "half-top", "thermal"]
  for (const format of formats) {
    const artifact = await getCanonicalInvoiceDocument(representative, settings, format)
    const validation = await validateCanonicalInvoicePdf(artifact.bytes, representative, settings, format)
    assert.equal(validation.pageCount, 1, `${format} must remain one page for the representative invoice`)
    assert.ok(validation.pageContentBytes[0] > 500, `${format} must not contain a blank first page`)
    assert.equal((await PDFDocument.load(artifact.bytes)).getTitle(), "Invoice INV-00005")
    const formatText = (await pdfText(artifact.bytes)).replace(/\s+/g, " ")
    assert.match(formatText, /Thank you/, `${format} must retain the exact primary footer`)
    assert.match(formatText, /Generated by Bezgrow/, `${format} must retain the exact attribution footer`)
  }

  const halfTop = await getCanonicalInvoiceDocument(invoice(20, true), settings, "half-top")
  const halfTopDocument = await PDFDocument.load(halfTop.bytes)
  const halfTopBoundary = halfTopDocument.getPage(0).getHeight() / 2
  const halfTopText = await pdfTextPositions(halfTop.bytes)
  assert.ok(halfTopText.length > 80, "Half A4 Top must substantially fill its intended content region")
  assert.ok(halfTopText.every((item) => item.y >= halfTopBoundary - 0.5), "Half A4 Top text must leave the lower physical half blank")
  assert.ok(Math.min(...halfTopText.map((item) => item.y)) < halfTopBoundary + 35, "Half A4 Top must use the lower edge of its top-half content region")

  const colour = await getCanonicalInvoiceDocument(representative, { ...settings, blackAndWhite: false }, "a4")
  const monochrome = await getCanonicalInvoiceDocument(representative, { ...settings, blackAndWhite: true }, "a4")
  const colourPage = (await PDFDocument.load(colour.bytes)).getPage(0)
  const monochromePage = (await PDFDocument.load(monochrome.bytes)).getPage(0)
  assert.equal(monochromePage.getWidth(), colourPage.getWidth(), "Black-and-white must not change invoice width")
  assert.equal(monochromePage.getHeight(), colourPage.getHeight(), "Black-and-white must not change invoice height")
  const monochromeText = (await pdfText(monochrome.bytes)).replace(/\s+/g, " ")
  assert.match(monochromeText, /INV-00005/)
  assert.match(monochromeText, /Grand Total/i)
  const monochromeColors = Array.from(drawingText(monochromePage).matchAll(
    /(-?(?:\d+(?:\.\d*)?|\.\d+))\s+(-?(?:\d+(?:\.\d*)?|\.\d+))\s+(-?(?:\d+(?:\.\d*)?|\.\d+))\s+(?:rg|RG)\b/g,
  ))
  assert.ok(monochromeColors.length > 10, "Black-and-white output must contain visible vector colours")
  for (const color of monochromeColors) {
    assert.equal(Number(color[1]), Number(color[2]), "Black-and-white red/green channels must match")
    assert.equal(Number(color[2]), Number(color[3]), "Black-and-white green/blue channels must match")
  }

  for (const format of formats.filter((value) => value !== "a4")) {
    const monochromeArtifact = await getCanonicalInvoiceDocument(representative, { ...settings, blackAndWhite: true }, format)
    const page = (await PDFDocument.load(monochromeArtifact.bytes)).getPage(0)
    const colors = Array.from(drawingText(page).matchAll(
      /(-?(?:\d+(?:\.\d*)?|\.\d+))\s+(-?(?:\d+(?:\.\d*)?|\.\d+))\s+(-?(?:\d+(?:\.\d*)?|\.\d+))\s+(?:rg|RG)\b/g,
    ))
    assert.ok(colors.length > 5, `${format} black-and-white output must contain visible vector colours`)
    for (const color of colors) {
      assert.equal(Number(color[1]), Number(color[2]), `${format} black-and-white red/green channels must match`)
      assert.equal(Number(color[2]), Number(color[3]), `${format} black-and-white green/blue channels must match`)
    }
  }

  const interstate = invoice(5, true)
  interstate.items = interstate.items.map((item) => ({
    ...item,
    cgstPercent: 0,
    cgstAmount: 0,
    sgstPercent: 0,
    sgstAmount: 0,
    igstPercent: 18,
    igstAmount: item.taxableValue * 0.18,
  }))
  interstate.totals.cgst = 0
  interstate.totals.sgst = 0
  interstate.totals.igst = interstate.items.reduce((sum, item) => sum + item.igstAmount, 0)
  const interstateText = (await pdfText((await getCanonicalInvoiceDocument(interstate, settings, "a4")).bytes)).replace(/\s+/g, " ")
  assert.match(interstateText, /IGST/, "Interstate A4 invoices must preserve the IGST accounting column and total")

  const withoutAssets = await getCanonicalInvoiceDocument(representative, {
    ...settings,
    showLogo: false,
    showQr: false,
    showBarcode: false,
  }, "a4")
  assert.ok(a4.bytes.byteLength > withoutAssets.bytes.byteLength, "Enabled logo/QR/barcode output must add document content")

  console.log(`canonical-invoice-document-ok formats=${formats.length} a4_bytes=${a4.bytes.byteLength} a4_content=${a4.pageContentBytes[0]} first_ms=${firstRenderMs.toFixed(1)} cached_ms=${cachedRenderMs.toFixed(3)}`)
}

void run()
